"""Tests for the Netscape cookies file validator."""

from __future__ import annotations

from pathlib import Path

import pytest

from vidscope.application.cookies_validator import (
    CookiesValidation,
    validate_cookies_file,
)


def _write(path: Path, content: str) -> Path:
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Happy path
# ---------------------------------------------------------------------------


class TestValidCookies:
    def test_minimal_valid_file(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\n"
            ".instagram.com\tTRUE\t/\tTRUE\t1893456000\tsessionid\tabc123\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 1
        assert result.reason == ""

    def test_multiple_valid_rows(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\n"
            ".instagram.com\tTRUE\t/\tTRUE\t1893456000\tsessionid\tabc\n"
            ".instagram.com\tTRUE\t/\tFALSE\t1893456000\tcsrftoken\tdef\n"
            ".instagram.com\tTRUE\t/\tTRUE\t1893456000\tds_user_id\t12345\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 3

    def test_no_header_still_valid(self, tmp_path: Path) -> None:
        # Some browser extensions skip the header altogether
        cookies = _write(
            tmp_path / "cookies.txt",
            ".instagram.com\tTRUE\t/\tTRUE\t1893456000\tsessionid\tabc\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 1

    def test_mixed_comments_and_rows(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\n"
            "# Generated by some browser extension\n"
            "\n"
            ".instagram.com\tTRUE\t/\tTRUE\t1893456000\tsessionid\tabc\n"
            "# A comment between rows\n"
            ".instagram.com\tTRUE\t/\tFALSE\t1893456000\tcsrftoken\tdef\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 2

    def test_empty_value_field_is_valid(self, tmp_path: Path) -> None:
        # Some cookies have an empty value (it's a valid case)
        cookies = _write(
            tmp_path / "cookies.txt",
            ".example.com\tTRUE\t/\tFALSE\t0\tflag\t\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 1

    def test_carriage_returns_handled(self, tmp_path: Path) -> None:
        # Windows-exported files may have CRLF line endings
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\r\n"
            ".example.com\tTRUE\t/\tTRUE\t0\tname\tvalue\r\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is True
        assert result.entries_count == 1


# ---------------------------------------------------------------------------
# Error paths
# ---------------------------------------------------------------------------


class TestInvalidCookies:
    def test_file_does_not_exist(self, tmp_path: Path) -> None:
        result = validate_cookies_file(tmp_path / "missing.txt")
        assert result.ok is False
        assert "does not exist" in result.reason
        assert result.entries_count == 0

    def test_path_is_directory(self, tmp_path: Path) -> None:
        result = validate_cookies_file(tmp_path)
        assert result.ok is False
        assert "not a regular file" in result.reason

    def test_empty_file(self, tmp_path: Path) -> None:
        cookies = _write(tmp_path / "cookies.txt", "")
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "empty" in result.reason

    def test_only_whitespace(self, tmp_path: Path) -> None:
        cookies = _write(tmp_path / "cookies.txt", "  \n\n  \n")
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "empty" in result.reason

    def test_only_comments(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\n"
            "# Just comments, no data\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "no cookie rows" in result.reason

    def test_malformed_rows_only(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "# Netscape HTTP Cookie File\n"
            "this is not a valid cookie line\n"
            "neither is this one\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "malformed" in result.reason

    def test_wrong_column_count(self, tmp_path: Path) -> None:
        # Only 5 columns instead of 7
        cookies = _write(
            tmp_path / "cookies.txt",
            ".example.com\tTRUE\t/\tTRUE\t0\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "malformed" in result.reason

    def test_empty_domain_column(self, tmp_path: Path) -> None:
        cookies = _write(
            tmp_path / "cookies.txt",
            "\tTRUE\t/\tTRUE\t0\tname\tvalue\n",
        )
        result = validate_cookies_file(cookies)
        assert result.ok is False
        assert "malformed" in result.reason


# ---------------------------------------------------------------------------
# CookiesValidation dataclass
# ---------------------------------------------------------------------------


class TestCookiesValidation:
    def test_is_frozen(self) -> None:
        v = CookiesValidation(ok=True, reason="", entries_count=1)
        with pytest.raises(AttributeError):
            v.ok = False  # type: ignore[misc]
